name: Tag releases
on:
  pull_request:
    types: closed

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Identify version bumps and tag the repo
        uses: deliveroo/label-semver-tagger.action@next
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          default: versionFile
          tag-format: v${version}
